FROM ubuntu:20.04

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
        build-essential \
        cmake \
        gdb \
        pylint \
        python3 \
        python3-dev \
        python3-numpy \
        python3-pep8 \
        python3-pip \
        python3-pybind11 \
        python3-pytest

#RUN pip3 install ...
