FROM python:3.10

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
        bash-completion \
        build-essential \
        cmake \
        curl \
        gdb \
        git \
        less \
        unzip \
        nano \
        vim \
        wget
